//
//  ViewController.swift
//  Maps Example
//
//  Created by Anton Antonov on 7/15/15.
//  Copyright (c) 2015 Anton Antonov. All rights reserved.
//

import UIKit
import MapKit

class ViewController: UIViewController, MKMapViewDelegate, CLLocationManagerDelegate {

  @IBOutlet weak var map: MKMapView!

  var locationManager = CLLocationManager()

  override func viewDidLoad() {
    super.viewDidLoad()

    locationManager.delegate = self
    locationManager.desiredAccuracy = kCLLocationAccuracyBest
    locationManager.requestWhenInUseAuthorization()
    locationManager.startUpdatingLocation()

    let latitude:CLLocationDegrees = 40.7
    let longitude:CLLocationDegrees = -73.9
    let latDelta:CLLocationDegrees = 0.01
    let lonDelta:CLLocationDegrees = 0.01

    let span:MKCoordinateSpan = MKCoordinateSpanMake(latDelta, lonDelta)
    let location:CLLocationCoordinate2D = CLLocationCoordinate2DMake(latitude, longitude)
    let region:MKCoordinateRegion = MKCoordinateRegionMake(location, span)

    map.setRegion(region, animated: true)

    var annotation = MKPointAnnotation()
    annotation.coordinate = location
    annotation.title = "This is"
    annotation.subtitle = "an ordinary annotation"

    map.addAnnotation(annotation)

    var uiLongPressRecognizer = UILongPressGestureRecognizer(target: self, action: "action:")
    uiLongPressRecognizer.minimumPressDuration = 2

    map.addGestureRecognizer(uiLongPressRecognizer)
  }

  func locationManager(manager: CLLocationManager!, didUpdateLocations locations: [AnyObject]!) {
    println(locations)

    let userLocation: CLLocation = locations[0] as! CLLocation
    let latitude = userLocation.coordinate.latitude
    let longitude = userLocation.coordinate.longitude
    let latDelta:CLLocationDegrees = 0.01
    let lonDelta:CLLocationDegrees = 0.01

    let span:MKCoordinateSpan = MKCoordinateSpanMake(latDelta, lonDelta)
    let location:CLLocationCoordinate2D = CLLocationCoordinate2DMake(latitude, longitude)
    let region:MKCoordinateRegion = MKCoordinateRegionMake(location, span)

    map.setRegion(region, animated: true)
  }

  func action(gestureRecognizer: UIGestureRecognizer) {
    let touchPoint = gestureRecognizer.locationInView(map)
    let newCoordinate: CLLocationCoordinate2D = map.convertPoint(touchPoint, toCoordinateFromView: map)

    var annotation = MKPointAnnotation()
    annotation.coordinate = newCoordinate
    annotation.title = "new place!"
    annotation.subtitle = "annotation generated by long press"
    map.addAnnotation(annotation)
  }

  override
  func didReceiveMemoryWarning() {
    super.didReceiveMemoryWarning()
    // Dispose of any resources that can be recreated.
  }


}

